import type { Metadata } from "next";
import "./globals.css";
import { NotifyProvider } from "./contexts/NotifyContext";
import Notify from "./components/Notify/Notify";
import { Space_Grotesk } from "next/font/google";
import { GlobalProvider } from "./contexts/GlobalContext";
import SystemSuspenseSettings from "./components/SystemSuspenseSettings";

const SpaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SpaceGrotesk.className} antialiased h-screen  bg-main`}
      >
        <GlobalProvider>
          <NotifyProvider>
            <Notify />
            <SystemSuspenseSettings />
            {children}
          </NotifyProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
